Merino/10 diseno inputs
ProyectoLabUCA/LaboratoriosInformaticaTemplate pull request #15
Opened 2023-04-29 21:02 UTC by GabrielMerinoUCA

Closed #10

2023-04-29 21:11 UTC, JezerM commented
Parece que creaste la rama a partir de `dev`. Los cambios en `dev` no han sido aplicados, y le corresponde a Leo.

Recomendaría hacer un rebase para eliminar los commits de la rama `dev`, o bien rehacer tus commits a partir de la rama `master`. La rama `dev` no debería de usarse en este repo, sino sólo en el LabInformatica.

2023-04-29 21:25 UTC, GabrielMerinoUCA commented
Supongo que en ese caso tendria que hacer otro PR? @JezerM

2023-04-29 21:25 UTC, JezerM commented
Puede hacerse en el mismo. Una vez hagas los arreglos, haces un `git push --force`.

2023-04-29 23:12 UTC, JezerM requested changes
Todavía hay ciertas cosas a mejorar en términos de lógica. En el diseño, está bien hecho.

2023-04-29 23:12 UTC, JezerM commented on Input Templates/README.md
Bueno, será revisarlo.

2023-04-29 23:12 UTC, JezerM commented on Input Templates/main.js
> +}
Aquí haría falta la validación en caso de ser menor o igual a 0. Y otra cosa, no mezcles tipos de datos, el `value`  es un String, luego no lo cambies a `Number` o puede haber confusiones.

Puede ser algo así:

```suggestion
function spinnerDown(inputClass) {
  const input = document.querySelector(`.${inputClass}`);
  const valueStr = input.value.replace(/\D/g, "");
  let value = parseInt(valueStr) - 1;
  
  if (value < 0) {
    value = 0;
  }
  
  input.value = value < 10 ? `0${value}` : value;
}
```

2023-04-29 23:12 UTC, JezerM commented on Input Templates/main.js
> +const ddlAmPm = document.getElementById('ddlAmPm')
El querySelector debería ser por ID individual, ya que en este caso al tener 2 btnSpinnerUp y otros 2 btnSpinnerDown, el valor de uno puede interferir en el otro~

2023-04-30 00:11 UTC, Amezal commented on Input Templates/README.md
Para este tipo de cosas pls usar el board y hablar con tu gerente para crear el item si es necesario, en el código no tienen visibilidad.

2023-04-30 00:12 UTC, Amezal commented on Input Templates/main.js
> +const ddlAmPm = document.getElementById('ddlAmPm')
De hecho no veo que se estén utilizando esas dos variables, si es así mejor eliminar.

2023-04-30 00:12 UTC, Amezal commented on Input Templates/main.js
> +const ddlAmPm = document.getElementById('ddlAmPm')
Usar nombres más descriptivos en las variables.

2023-04-30 00:14 UTC, Amezal commented on Input Templates/main.js
> +    console.log("Hola")
Eliminar console.log

2023-04-30 00:15 UTC, Amezal commented on solicitudes.css
> +input[type=number]::-webkit-outer-spin-button {
Indentación

2023-04-30 00:17 UTC, Amezal commented
Esto pasa al darle hacia abajo en el input del spinner
![image](https://user-images.githubusercontent.com/83527828/235329428-6169da4a-a281-45ed-bf63-24fda75d181c.png)

2023-04-30 00:58 UTC, GabrielMerinoUCA commented
Creo que ya resolvi todo

2023-04-30 01:35 UTC, JezerM approved these changes
Me parece bien~

2023-04-30 04:17 UTC, merged