Creación de la vista principal de los laboratorios
ProyectoLabUCA/LaboratoriosInformaticaTemplate pull request #25
Opened 2023-04-30 06:30 UTC by JorgeCh1

Closes #24

2023-04-30 06:47 UTC, JezerM requested changes
El padding de las cards no es correcto, se solucionaría con un `p-3` en cada card. Además, el contenedor de las cards no es responsive, por lo que en dispositivos pequeños puede verse mal, y en general es algo inconsistente. Sería revisar eso.

<img width="1440" alt="Captura de pantalla 2023-04-30 a la(s) 00 42 55" src="https://user-images.githubusercontent.com/59768785/235339681-78d3fef4-4e48-4e42-80e5-dbe967a5070c.png">

2023-04-30 06:47 UTC, JezerM commented on laboratoriosIndex.html
> +          <div class="card">
En el caso de los Cards, debes de usar los ejemplos propuestos en el `index.html`.

```suggestion
          <div class="card border-0 rounded-xl shadow p-3 d-flex align-items-center">
```

2023-05-01 16:46 UTC, Amezal commented on laboratoriosIndex.html
> +          <div class="card">
Same, me falla entre los breakpoints de medium (768px) y extra large (1200px)

2023-05-01 16:48 UTC, Amezal commented on laboratoriosIndex.html
> +  <script>
Incluir scripts a como se hace con los últimos cambios en master

2023-05-01 17:58 UTC, Amezal commented on scripts/laboratorio.js
> +  console.log(newQuantity);
Eliminar console.log

2023-05-01 17:58 UTC, Amezal commented on scripts/laboratorio.js
> +  console.log(newValue);
x2

2023-05-01 17:58 UTC, Amezal commented on scripts/laboratorio.js
> +  console.log(newQuantity);
x3

2023-05-01 17:58 UTC, Amezal commented on scripts/laboratorio.js
> +  console.log(newValue);
x4

2023-05-01 19:36 UTC, LeoncioPavon commented
Hay conflictos con un archivo con ese mismo nombre dentro de Scripts que ya se encuentra en master. (scripts/laboratorio.js)

2023-05-01 22:11 UTC, Amezal approved these changes

2023-05-01 22:24 UTC, LeoncioPavon approved these changes
Realizó los cambios correctamente

2023-05-02 04:27 UTC, JezerM approved these changes
Me parece

2023-05-02 04:27 UTC, merged