Creacion de Editar Laboratorio Otro No Computer
ProyectoLabUCA/LaboratoriosInformaticaTemplate pull request #34
Opened 2023-04-30 19:22 UTC by JanCarlosPM

Closes #33

2023-04-30 20:18 UTC, LeoncioPavon requested changes
Hacer los cambios sugeridos para aprovar tu tarea.

2023-04-30 20:18 UTC, LeoncioPavon commented on laboratorio2.html
> +
La implementación de este script no es correcta y está de más, ya que no tiene funcionalidad alguna, es mejor eliminarlo.

2023-04-30 20:18 UTC, LeoncioPavon commented on laboratorio2.html
> +            </div>
Se muestra el borde del dialog  antes de pulsar el espacio vacío lo cual es importante ocultar.

2023-05-01 00:00 UTC, JanCarlosPM reviewed
close #33

2023-05-01 01:25 UTC, JezerM approved these changes
Me parece

2023-05-01 01:58 UTC, LeoncioPavon approved these changes

2023-05-01 01:58 UTC, merged