Diseño del Dashboard (Técnico)
ProyectoLabUCA/LaboratoriosInformaticaTemplate pull request #35
Opened 2023-05-01 01:41 UTC by JezerM

Closes #23

2023-05-01 04:06 UTC, GabrielMerinoUCA commented on index.html
>                    class="card border-0 rounded-xl shadow p-4 d-flex align-items-center"
El card "Uso de laboratorios" tiene un responsive distinto al de los otros cards. No se si es mi telefono, pero cuando carga la pagina, el card pareciese no tener "margin" derecho.

2023-05-01 04:09 UTC, GabrielMerinoUCA commented on index.html
>                  <div class="row gap-3 no-gutters">
Pensaba que los cards "Ver solicitudes" y "Crear solicitudes" podrian ser etiquetas '<a>'

2023-05-01 04:12 UTC, GabrielMerinoUCA commented on index.html
> +                      <div class="item"><i class="fa-thin fa-circle" style="color: #ededed;"></i></div>
los iconos que simbolizan espacio nulo del card "Uso de laboratorios" no parecen cargar correctamente en firefox

2023-05-01 04:22 UTC, GabrielMerinoUCA commented on index.html
>                    class="card border-0 rounded-xl shadow p-4 d-flex align-items-center"
Bueno viendolo mejor, quisas el problema sea del div que encapsula a los 3 cards de la derecha por la linea 209.
"
<div class="col-lg-6">
              <div class="d-flex flex-column gap-3 ml-lg-4 h-100 w-max-content min-w-100">...
"

2023-05-01 17:17 UTC, Amezal requested changes

2023-05-01 17:17 UTC, Amezal commented on index.html
> +                    <h6 class="font-weight-bold">Crear solicitudes</h5>
h6 y h5 en las tags

2023-05-01 17:17 UTC, Amezal commented on index.html
> +                    <h6 class="font-weight-bold">Ver solicitudes</h5>
h6 y h5 en las tags

2023-05-02 04:15 UTC, JezerM commented on index.html
> +                    <h6 class="font-weight-bold">Crear solicitudes</h5>
Cierto, se me pasó xd

2023-05-02 04:18 UTC, JezerM commented on index.html
> +                      <div class="item"><i class="fa-thin fa-circle" style="color: #ededed;"></i></div>
Sí, parece que el icono no es el indicado, sin embargo tales iconos sólo están para rellenar, al final no habría iconos en tales espacios vacíos.

2023-05-02 04:19 UTC, JezerM commented on index.html
>                    class="card border-0 rounded-xl shadow p-4 d-flex align-items-center"
Yep, el punto de este diseño es, en caso de que el dispositivo sea demasiado pequeño, que permita hacer un scroll horizontal para poder visualizar el resto del contenido sin que este se vea afectado.

2023-05-02 04:23 UTC, JezerM commented on index.html
>                  <div class="row gap-3 no-gutters">
¿Qué tipo de etiquetas?

2023-05-02 04:29 UTC, GabrielMerinoUCA commented on index.html
>                  <div class="row gap-3 no-gutters">
Bueno parece que no se envio esa ultima parte. Etiqueta "a"

2023-05-02 04:37 UTC, JezerM commented on index.html
>                  <div class="row gap-3 no-gutters">
Cierto, lo implementaré.

2023-05-02 04:53 UTC, GabrielMerinoUCA approved these changes
Lo veo bien

2023-05-02 18:37 UTC, Amezal approved these changes

2023-05-02 18:37 UTC, merged