Mendoza/19 diseno pagina ajuste
ProyectoLabUCA/LaboratoriosInformaticaTemplate pull request #37
Opened 2023-05-01 05:37 UTC by Alcides4002

closed #19

2023-05-02 03:50 UTC, Gabox-28 commented
Creo que deberias ponerle un margen a los inputs, de manera que se note la jerarquía.
![Screenshot_1](https://user-images.githubusercontent.com/86949735/235567405-d1b813af-c525-4765-82f3-f091cb7e38c5.png)

Te recomiendo agruparlos dentro de un contenedor y al contenedor le pones un margen

2023-05-02 04:36 UTC, JezerM requested changes
Hay algunos cuantos errores ortográficos y es posible que se me haya pasado alguno, recomendaría revisarlo bien. Además, a como comentó Gabriel, le haría falta un margen izquierdo entre cada sección de Ajustes e Inputs para resaltar la jerarquía de los elementos.

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +          <label for="dias-anticipacion">Dias de anticipacion de prestamo</label>
```suggestion
          <label for="dias-anticipacion">Días de anticipación de préstamo</label>
```

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +          <p class="ExplicacionDeAjuste my-2">Cuantos dias antes puede un estudiante para solicitar un prestamo.</p>
```suggestion
          <p class="ExplicacionDeAjuste my-2">Cuántos días antes puede un estudiante solicitar un préstamo.</p>
```

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +          <label for="Timepo-MX-R-Diarias" class="my-2">Tiempo maximo de reservaciones diarias</label>
```suggestion
          <label for="Timepo-MX-R-Diarias" class="my-2">Tiempo máximo de reservaciones diarias</label>
```

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +            <p class="ExplicacionDeAjuste my-2">El tiempo maximo que un Estudiante puede solcitar un dia. </p>
```suggestion
            <p class="ExplicacionDeAjuste my-2">El tiempo máximo que un Estudiante puede solicitar en un día.</p>
```

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +            <p class="ExplicacionDeAjuste my-2">La cantidad maxima de solucitudes que un Estudiante puede realizar.</p>
```suggestion
            <p class="ExplicacionDeAjuste my-2">La cantidad máxima de solicitudes que un Estudiante puede realizar.</p>
```

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +           </div>
En este apartado, hay mucho margen entre ambos elementos. Recomendaría no usar el `justify-content-between` y tan sólo añadir un gap o un margen entre ambos elementos.

La hora de apertura y la hora de cierre no deberían verse así:
<img width="629" alt="Captura de pantalla 2023-05-01 a la(s) 22 28 54" src="https://user-images.githubusercontent.com/59768785/235579911-b8e23454-8846-4bad-8920-61fe3981fa34.png">

2023-05-02 04:36 UTC, JezerM commented on ajuste.html
> +          <p class="font-weight-bold">Ajustes de prestamo</p>
```suggestion
          <p class="font-weight-bold">Ajustes de préstamo</p>
```

2023-05-02 06:05 UTC, LeoncioPavon commented on ajuste.html
> +           </div>
O con un form-inline

2023-05-03 05:06 UTC, JezerM approved these changes
Me parece bien

2023-05-03 05:06 UTC, merged